### ISSUE TITLE
crashes with images, pdf

### ISSUE THREAD

**Issue by ShinKaz** [joel16/NX-Shell#45]
Hi ! thanks for you guys work !

- been trying to read some manga chapters, but get a **crash after reading 3 images**.
- been trying to view the images in portrait mode but Y just does a mirror symmetry. 
- converted my chapter as one pdf file, pressed Y, rotation to portrait works but it's not centered, get black at the bottom and the top is cut. (and then it just crashes like it did after 3 images)

NX-shell is ran from an HBL nsp (otherwise I get the same crashed but with atmosphere error log)

here are the files I'm talking about : https://www94.zippyshare.com/v/RwKmDq2G/file.html
(those were originally .webp, converted them to jpg.)

Also, **[Feature Request]** . would it be possible to add webp support ? thanks a lot :)

**Comment by denilugito** [comment]
> Hi ! thanks for you guys work !
> 
> * been trying to read some manga chapters, but get a **crash after reading 3 images**.
> * been trying to view the images in portrait mode but Y just does a mirror symmetry.
> * converted my chapter as one pdf file, pressed Y, rotation to portrait works but it's not centered, get black at the bottom and the top is cut. (and then it just crashes like it did after 3 images)
> 
> NX-shell is ran from an HBL nsp (otherwise I get the same crashed but with atmosphere error log)
> 
> here are the files I'm talking about : https://www94.zippyshare.com/v/RwKmDq2G/file.html
> (those were originally .webp, converted them to jpg.)
> 
> Also, **[Feature Request]** . would it be possible to add webp support ? thanks a lot :)

Also want to highlight this issue.. it also happened to me after rotating images. After rotating the image soon it got crashed with error 2168-0002.. Thanks

**Comment by Klauserus** [comment]
Hi

Nx-Shell crashes on my switch, too. When i try to load this image:
[https://ufile.io/q4nl6](https://ufile.io/q4nl6)

Switch 7.0.1 AMS 0.8.4 and Hekate 4.8

thx

**Comment by RevanSolo25** [comment]
Also had crashes when looking jpegs in album in nintendo dir. But only on lastest version of NX Shell, previous version works fine, or more specificly it doesn't make crashes, only stops read pictures sometimes (read all pictures as a grey screen), but that  fixes after exiting from NX-Shell, and reopening it again.

**Comment by Agito-kun** [comment]
The NX-shell crashed for me too. After I have copy a folder with save and images and a long name i see a atmosphere error. At the root of the SD had NX-shell no problem this it. At the Pfad i have paste also no problem - so long the folder who i have paste non exist. I musst delete the folder the the pc, to fix the crash of NX-shell at starup. I think because NX-shell start at this place, the crash come now at startup.

Update:
Then i delete just a part of the problem folder, crash it instantly too. I must delete the complete structure that was pastet, restart without and first then will it be again accepted - Why!?
After several attempts, I have now found out that the "blanks" combined with "." are the reason for the crash. Avoiding spaces or points prevents the crash.
It can be changed to the folder, and actions can be performed. But at changing in the parent folder or sporadically already when switching he comes the crash.
Older versions of NX-Shell and Atmosphere did not have the problem.


Switch 8.0.1 with exFAT AMS 0.8.10 Hekate 4.10.1 Kosmos 12.2 with es
Error Code: 2168-0002 (0x4a8)
Title: 010000000000100D

**Comment by Tensepanda** [comment]
I'm getting the same error code, but it's when I try to install NX Shell from the Homebrew App. 
It downloads til about 70% and then bam. 

Error : 2168-0002 (0x4a8)
Title: 010000000000100D

Firmware 8.1.0 Atmosphere 0.9.4-master......

> The NX-shell crashed for me too. After I have copy a folder with save and images and a long name i see a atmosphere error. At the root of the SD had NX-shell no problem this it. At the Pfad i have paste also no problem - so long the folder who i have paste non exist. I musst delete the folder the the pc, to fix the crash of NX-shell at starup. I think because NX-shell start at this place, the crash come now at startup.
> 
> Update:
> Then i delete just a part of the problem folder, crash it instantly too. I must delete the complete structure that was pastet, restart without and first then will it be again accepted - Why!?
> After several attempts, I have now found out that the "blanks" combined with "." are the reason for the crash. Avoiding spaces or points prevents the crash.
> It can be changed to the folder, and actions can be performed. But at changing in the parent folder or sporadically already when switching he comes the crash.
> Older versions of NX-Shell and Atmosphere did not have the problem.
> 
> Switch 8.0.1 with exFAT AMS 0.8.10 Hekate 4.10.1 Kosmos 12.2 with es
> Error Code: 2168-0002 (0x4a8)
> Title: 010000000000100D

**Comment by joel16** [comment]
@Tensepanda you should make that issue with the homebrew store Devs. I'm not affiliated with them, and I'd usually recommend downloading straight from GitHub.

Also closing this since the PDF feature has been removed indefinitely.
